### ISSUE TITLE
application exits with X error message

### ISSUE THREAD

**Issue by mindrunner** [jcs/xdimmer#2]
le@w530 ~/src/xdimmer $ ./xdimmer -p 50 -t 1
    X Error of failed request:  BadValue (integer parameter out of range for operation)
      Major opcode of failed request:  139 (RANDR)
      Minor opcode of failed request:  13 (RRChangeOutputProperty)
      Value in failed request:  0x43
      Serial number of failed request:  25
      Current serial number in output stream:  26

**Comment by jcs** [comment]
What does `xrandr` look like and does `xdimmer -d` print anything useful?

**Comment by mindrunner** [comment]
Thats my xrandr output:

    le@w530 ~/src/latex-makefile $ xrandr 
    Screen 0: minimum 8 x 8, current 1920 x 1080, maximum 32767 x 32767
    LVDS1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 344mm x 193mm
       1920x1080     60.00*+  50.00  
       1400x1050     59.98  
       1280x1024     60.02  
       1280x960      60.00  
       1024x768      60.00  
       800x600       60.32    56.25  
       640x480       59.94  
    VGA1 disconnected (normal left inverted right x axis y axis)
    VIRTUAL1 disconnected (normal left inverted right x axis y axis)

////

    xdimmer -d -t1 

dims my screen down to lowest brightness level and up to highest after moving the mouse. However playing around with the `-p` switch results in either
- dimming to lowest brightness
or
- application exiting (see above)

Which of these results happen depends on the current brightness and the `-p` switch. Seems like the crash is more likely the higher the p-value and the lower the current brightness is.

**Comment by jcs** [comment]
`-d` should print the value it's about to use to the call that crashes the app, so can you show what it prints before it crashes?

**Comment by mindrunner** [comment]
```
le@w530 ~/src/xdimmer $ ./xdimmer -d -p50 -t1
dimming to 50% in 1 secs
idle counter reached 1000ms
dimming to 50
stepping from 15 to 7 in increments of 1 (10 steps)
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  139 (RANDR)
  Minor opcode of failed request:  13 (RRChangeOutputProperty)
  Value in failed request:  0x43
  Serial number of failed request:  25
  Current serial number in output stream:  26
```
