### ISSUE TITLE
Keyboard backlight not recognized

### ISSUE THREAD

**Issue by unix4you2** [jcs/xdimmer#3]
Hi there.

I'm using an OpenBSD 6.9 fresh install in a Azuz ZenBook UX433FN  and after  make and run this tool to turn on my keyboard backlight I'm getting this message: 
**xdimmer: WSKBDIO_GETBACKLIGHT failed: Inappropriate ioctl for device**

Does anybody know what is missing or happening?  Thanks a lot.

PD: Under FreeBSD or Linux backlight works like a charm.

**Comment by jcs** [comment]
I'm guessing `wsconsctl keyboard.backlight` doesn't work either.

For an Asus, OpenBSD would probably need an ACPI WMI driver to hook up the keyboard backlight which Linux has and I'm assuming FreeBSD does if it works there.  Only `acpithinkpad` and `asmc` on OpenBSD hook up keyboard backlight controls.
